services:
  productservice.api:
    image: ${PRODUCT_IMAGE_TAG-}
    container_name: productservice.api
    depends_on:
      db:
        condition: service_healthy
    networks:
      - appnet

  orderservice.api:
    image: ${ORDER_IMAGE_TAG-}
    container_name: orderservice.api
    depends_on:
      db:
        condition: service_healthy
    networks:
      - appnet

  db:
    image: postgres:16-alpine 
    container_name: postgresdb
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Romari0!
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - appnet
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  appnet:
    driver: bridge

volumes:
  postgres_data: