services:
  productservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging 
      - ConnectionStrings__DefaultConnection=Server=db;Database=ProductDb;User Id=sa;Password=Your_strong!Passw0rd123A;Encrypt=False
    volumes: []
    
    deploy:
      resources:
        limits:
          memory: 512M
      restart_policy:
        condition: on-failure
    
  orderservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ConnectionStrings__DefaultConnection=Server=db;Database=OrderDb;User Id=sa;Password=Your_strong!Passw0rd123A;Encrypt=False
    volumes: []
    
    deploy:
      resources:
        limits:
          memory: 512M
      restart_policy:
        condition: on-failure

  db:
    ports: []

    deploy:
      resources:
        limits:
          memory: 1024M
      restart_policy:
        condition: always