services:
  productservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging 
    
    volumes: []
    
    deploy:
      resources:
        limits:
          memory: 512M
      restart_policy:
        condition: on_failure
    
  orderservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging

    volumes: []
    
    deploy:
      resources:
        limits:
          memory: 512M
      restart_policy:
        condition: on_failure

  db:
    ports: []

    deploy:
      resources:
        limits:
          memory: 1024M
      restart_policy:
        condition: always