services:
  productservice.api:
    image: tst-productserviceapi:latest
    build:
      context: .
      dockerfile: ProductService/ProductService.API/Dockerfile
    env_file:
      - ProductService/.env 
    environment:
      - ASPNETCORE_ENVIRONMENT=Testing
    ports:
      - "8082:8080"
    volumes:
      - ./ProductService/ProductService.API:/src/ProductService.API 

  orderservice.api:
    image: tst-orderservice:latest
    build:
      context: .
      dockerfile: OrderService/OrderService.API/Dockerfile
    env_file:
      - OrderService/.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Testing
    ports:
      - "8081:8080"
    volumes:
      - ./OrderService/OrderService.API:/src/OrderService.API

  redis:
    image: redis:latest
    container_name: redis-local
    ports:
        - "6379:6379"
    networks:
        - appnet
    healthcheck:
        test: ["CMD", "redis-cli", "ping"]
        interval: 10s
        timeout: 3s
        retries: 3
        start_period: 15s
    deploy:
      resources:
        limits:
          memory: 256M