services:
  productservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging 
      - ConnectionStrings__DefaultConnection=Host=postgresdb;Port=5432;Database=product;Username=postgres;Password=Romari0!;
    volumes: []
    
    deploy:
      resources:
        limits:
          memory: 512M
      restart_policy:
        condition: on-failure
    
  orderservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ConnectionStrings__DefaultConnection=Host=postgresdb;Port=5432;Database=order;Username=postgres;Password=Romari0!;

    volumes: []
    
    deploy:
      resources:
        limits:
          memory: 512M
      restart_policy:
        condition: on-failure

  db:
    ports: []

    deploy:
      restart_policy:
        condition: always