services:
  productservice.api:
    image: ${IMAGE_TAG:-base}-productserviceapi:latest
    build:
      context: .
      dockerfile: ProductService/ProductService.API/Dockerfile
    container_name: productservice.api
    depends_on:
      db:
        condition: service_healthy
    networks:
      - appnet

  orderservice.api:
    image: ${IMAGE_TAG:-base}-orderserviceapi:latest
    build:
      context: .
      dockerfile: OrderService/OrderService.API/Dockerfile
    container_name: orderservice.api
    depends_on:
      db:
        condition: service_healthy
    networks:
      - appnet

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Your_strong!Passw0rd
    healthcheck:
      test: ["CMD-SHELL", "pgrep sqlservr"]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 30s
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

volumes:
  mssql_data: