services:
  productservice.api:
    image: ${PRODUCT_IMAGE_TAG}
    container_name: productservice.api
    depends_on:
      db:
        condition: service_healthy
    networks:
      - appnet

  orderservice.api:
    image: ${ORDER_IMAGE_TAG}
    container_name: orderservice.api
    depends_on:
      db:
        condition: service_healthy
    networks:
      - appnet

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Your_strong!Passw0rd123A
      - MSSQL_LCFLATFILE_ROOT=/var/opt/mssql/data
    healthcheck:
      test: ["CMD-SHELL", "pgrep sqlservr"]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 30s
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

volumes:
  mssql_data: